### ISSUE TITLE
Dodat URL v Facebook appu

### ISSUE THREAD

**Issue by mzgajner** [danesjenovdan/twito#2]
Nimam pojma, kako točno to deluje, ampak kolikor vidim imamo v vseh facebook share URLjih nek App id - predvidevam, da je to ID od DJND FB pejdža/appa.

Isti ID sem uporabil tudi na twitotu, ampak zaenkrat fukne:
```
Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings.
```
Predvidevam, da mora nekdo, ki je FB admin, dodat twito.si na nek whitelist?

**Comment by muki** [comment]
Maš prav, sem predal naprej ljudem, ki imajo dostop. :)
